# spring:
#   datasource:
#     username: root
#     password: Number#001
#     url: jdbc:mysql://localhost:3306/alphabet
#     driver-class-name: com.my.sql.cj.jdbc.Driver
#   jpa:
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#     properties.hibernate.dialect: org.hibernate.dialect.MYSQL